class Scoreboard:
	def getTeams(self):
		...

	def resetPlayerScore(self, playerName, objective):
		...

	def getAllPlayerScores(self, objective):
		...

	def removeTeam(self, team):
		...

	def containsObjective(self, name):
		...

	def addObjective(self, name, criterion, displayName, renderType):
		...

	def removePlayerFromTeam(self, playerName, team):
		...

	def getObjectives(self):
		...

	def addPlayerToTeam(self, playerName, team):
		...

	def clearPlayerTeam(self, playerName):
		...

	def getObjectiveNames(self):
		...

	def getTeam(self, name):
		...

	def resetEntityScore(self, entity):
		...

	def getObjective(self, name):
		...

	def addTeam(self, name):
		...

	def getTeamNames(self):
		...

	def removeObjective(self, objective):
		...

	def getPlayerScore(self, name, objective):
		...

	def getPlayerTeam(self, name):
		...
