class Team:
	def setSuffix(self, suffix):
		...

	def setShowFriendlyInvisibles(self, showFriendlyInvisibles):
		...

	def setPrefix(self, prefix):
		...

	def shouldShowFriendlyInvisibles(self):
		...

	def setNameTagVisibilityRule(self, nameTagVisibilityRule):
		...

	def setFriendlyFireAllowed(self, friendlyFireAllowed):
		...

	def setDisplayName(self, displayName):
		...

	def setDeathMessageVisibilityRule(self, deathMessageVisibilityRule):
		...

	def setColor(self, formatting):
		...

	def setCollisionRule(self, collisionRule):
		...

	def isFriendlyFireAllowed(self):
		...

	def getSuffix(self):
		...

	def getPlayerList(self):
		...

	def getPrefix(self):
		...

	def getNameTagVisibilityRule(self):
		...

	def getName(self):
		...

	def getDisplayName(self):
		...

	def getDeathMessageVisibilityRule(self):
		...

	def getColor(self):
		...

	def getCollisionRule(self):
		...
