class Server:
    def getPlayerManager(self):
        ...

    def getDefaultGameMode(self):
        ...

    def getForcedGameMode(self):
        ...

    def getScoreboard(self):
        ...

    def getMaxWorldBorderRadius(self):
        ...

    def getServerIP(self):
        ...

    def getWorld(self, world):
        ...

    def getServerMOTD(self):
        ...

    def getServerPort(self):
        ...

    def getSpawnProtectionRadius(self):
        ...

    def getSpawnRadius(self, world):
        ...

    def getVersion(self):
        ...

    def isFlightEnabled(self):
        ...

    def isHardcore(self):
        ...

    def isMonsterSpawningEnabled(self):
        ...

    def isNetherAllowed(self):
        ...

    def isPVPEnabled(self):
        ...

    def isSingleplayer(self):
        ...

    def openToLAN(self, gameMode, cheatsAllowed, port):
        ...

    def setDefaultGameMode(self, defaultGameMode):
        ...

    def setDifficulty(self, difficulty):
        ...

    def setDifficultyLocked(self, difficultyLocked):
        ...
