class Entity:
    def __init__(self, entity, world):
        ...

    def addVelocity(self, velocity):
        ...

    def canFreeze(self):
        ...

    def canUsePortals(self):
        ...

    def collidesWith(self, entity):
        ...

    def damage(self, damageSource, amount):
        ...

    def dismountVehicle(self):
        ...

    def distanceTo(self, entity):
        ...

    def extinguish(self):
        ...

    def extinguishWithSound(self):
        ...

    def getArmorItems(self):
        ...

    def getBlockPos(self):
        ...

    def getCommandTags(self):
        ...

    def getCustomName(self):
        ...

    def getDisplayName(self):
        ...

    def getHandItems(self):
        ...

    def getName(self):
        ...

    def getPosition(self):
        ...

    def getVehicle(self):
        ...

    def getVelocity(self):
        ...

    def getX(self):
        ...

    def getY(self):
        ...

    def getZ(self):
        ...

    def hasCustomName(self):
        ...

    def hasNoGravity(self):
        ...

    def hasPassenger(self, entity):
        ...

    def hasPassengers(self):
        ...

    def hasPermissionLevel(self, level):
        ...

    def hasPortalCooldown(self):
        ...

    def hasVehicle(self):
        ...

    def isAlive(self):
        ...

    def isCollidable(self):
        ...

    def isCrawling(self):
        ...

    def isCustomNameVisible(self):
        ...

    def isDead(self):
        ...

    def isInLava(self):
        ...

    def isInRain(self):
        ...

    def isInsidePortal(self):
        ...

    def isInsideWater(self):
        ...

    def isOnGround(self):
        ...

    def isSpectator(self):
        ...

    def isSubmergedInWater(self):
        ...

    def isVisible(self):
        ...

    def lookAt(self, x, y, z):
        ...

    def removeAllPassengers(self):
        ...

    def removePassenger(self, entity):
        ...

    def removePermissionLevel(self, level):
        ...

    def ride(self, entity):
        ...

    def setPosition(self, x, y, z):
        ...

    def setCustomName(self, customName):
        ...

    def setCustomNameVisible(self, visible):
        ...

    def setGlowing(self, glowing):
        ...

    def setInvisible(self, invisible):
        ...

    def setInvulnerable(self, invulnerable):
        ...

    def setMotion(self, motion):
        ...

    def setNoGravity(self, noGravity):
        ...

    def setSilent(self, silent):
        ...

    def setSneaking(self, sneaking):
        ...

    def setSprinting(self, sprinting):
        ...

    def startRiding(self, entity):
        ...

    def stopRiding(self):
        ...

    def teleport(self, position):
        ...
