class Entities:
    """
    The Entities class represents different types of entities in Minecraft.
    """

    ALLAY: object
    AREA_EFFECT_CLOUD: object
    ARMOR_STAND: object
    ARROW: object
    AXOLOTL: object
    BAT: object
    BEE: object
    BLAZE: object
    BLOCK_DISPLAY: object
    BOAT: object
    CAMEL: object
    CAT: object
    CAVE_SPIDER: object
    CHEST_BOAT: object
    CHEST_MINECART: object
    CHICKEN: object
    COD: object
    COMMAND_BLOCK_MINECART: object
    COW: object
    CREEPER: object
    DOLPHIN: object
    DONKEY: object
    DRAGON_FIREBALL: object
    DROWNED: object
    EGG: object
    ELDER_GUARDIAN: object
    END_CRYSTAL: object
    ENDER_DRAGON: object
    ENDER_PEARL: object
    ENDERMAN: object
    ENDERMITE: object
    EVOKER: object
    EVOKER_FANGS: object
    EXPERIENCE_BOTTLE: object
    EXPERIENCE_ORB: object
    EYE_OF_ENDER: object
    FALLING_BLOCK: object
    FIREWORK_ROCKET: object
    FOX: object
    FROG: object
    FURNACE_MINECART: object
    GHAST: object
    GIANT: object
    GLOW_ITEM_FRAME: object
    GLOW_SQUID: object
    GOAT: object
    GUARDIAN: object
    HOGLIN: object
    HOPPER_MINECART: object
    HORSE: object
    HUSK: object
    ILLUSIONER: object
    INTERACTION: object
    IRON_GOLEM: object
    ITEM: object
    ITEM_DISPLAY: object
    ITEM_FRAME: object
    FIREBALL: object
    LEASH_KNOT: object
    LIGHTNING_BOLT: object
    LLAMA: object
    LLAMA_SPIT: object
    MAGMA_CUBE: object
    MARKER: object
    MINECART: object
    MOOSHROOM: object
    MULE: object
    OCELOT: object
    PAINTING: object
    PANDA: object
    PARROT: object
    PHANTOM: object
    PIG: object
    PIGLIN: object
    PIGLIN_BRUTE: object
    PILLAGER: object
    POLAR_BEAR: object
    POTION: object
    PUFFERFISH: object
    RABBIT: object
    RAVAGER: object
    SALMON: object
    SHEEP: object
    SHULKER: object
    SHULKER_BULLET: object
    SILVERFISH: object
    SKELETON: object
    SKELETON_HORSE: object
    SLIME: object
    SMALL_FIREBALL: object
    SNIFFER: object
    SNOW_GOLEM: object
    SNOWBALL: object
    SPAWNER_MINECART: object
    SPECTRAL_ARROW: object
    SPIDER: object
    SQUID: object
    STRAY: object
    STRIDER: object
    TADPOLE: object
    TEXT_DISPLAY: object
    TNT: object
    TNT_MINECART: object
    TRADER_LLAMA: object
    TRIDENT: object
    TROPICAL_FISH: object
    TURTLE: object
    VEX: object
    VILLAGER: object
    VINDICATOR: object
    WANDERING_TRADER: object
    WARDEN: object
    WITCH: object
    WITHER: object
    WITHER_SKELETON: object
    WITHER_SKULL: object
    WOLF: object
    ZOGLIN: object
    ZOMBIE: object
    ZOMBIE_HORSE: object
    ZOMBIE_VILLAGER: object
    ZOMBIFIED_PIGLIN: object
    PLAYER: object
    FISHING_BOBBER: object
