from .entity import Entity


class LivingEntity(Entity):
    def addStatusEffect(self, effect, duration, amplifier, visible):
        ...

    def canBreatheInWater(self):
        ...

    def canHaveStatusEffect(self, effect):
        ...

    def canSee(self, entity):
        ...

    def canTakeDamage(self):
        ...

    def clearStatusEffects(self):
        ...

    def damageArmor(self, damageSource, amount):
        ...

    def damageHelmet(self, damageSource, amount):
        ...

    def damageShield(self, amount):
        ...

    def eatFood(self, stack):
        ...

    def getAbsorptionAmount(self):
        ...

    def getActiveHand(self):
        ...

    def getActiveItem(self):
        ...

    def getArmor(self):
        ...

    def getAttacker(self):
        ...

    def getAttacking(self):
        ...

    def getMainArm(self):
        ...

    def getMainHandStack(self):
        ...

    def getMaxHealth(self):
        ...

    def getMovementSpeed(self):
        ...

    def getScaleFactor(self):
        ...

    def getStackInHand(self, hand):
        ...

    def getStatusEffect(self, effect):
        ...

    def getStatusEffects(self):
        ...

    def getStuckArrowCount(self):
        ...

    def hasStatusEffect(self, effect):
        ...

    def heal(self, amount):
        ...

    def getHealth(self):
        ...

    def isAffectedBySplashPotions(self):
        ...

    def isBaby(self):
        ...

    def isBlocking(self):
        ...

    def isClimbing(self):
        ...

    def isDead(self):
        ...

    def isFallFlying(self):
        ...

    def isHolding(self, item):
        ...

    def isHoldingOntoLadder(self):
        ...

    def isHurtByWater(self):
        ...

    def isMobOrPlayer(self):
        ...

    def isSleeping(self):
        ...

    def isUndead(self):
        ...

    def isUsingItem(self):
        ...

    def isUsingRiptide(self):
        ...

    def removeStatusEffect(self, effect):
        ...

    def setAbsorptionAmount(self, amount):
        ...

    def setAttacker(self, entity):
        ...

    def setAttacking(self, entity):
        ...

    def setCurrentHand(self, hand):
        ...

    def setHealth(self, amount):
        ...

    def setJumping(self, jumping):
        ...

    def setMovementSpeed(self, movementSpeed):
        ...

    def setStackInHand(self, hand, stack):
        ...

    def setStingerCount(self, stingerCount):
        ...

    def setStuckArrowCount(self, stuckArrowCount):
        ...

    def shouldDisplaySoulSpeedEffects(self):
        ...

    def shouldDropXp(self):
        ...

    def swingHand(self, hand):
        ...

    def takeKnockback(self, strength, x, z):
        ...

    def teleport(self, position):
        ...

    def tiltScreen(self, deltaX, deltaY):
        ...
