class Particles:
	AMBIENT_ENTITY_EFFECT: object
	ANGRY_VILLAGER: object
	BUBBLE: object
	CLOUD: object
	CRIT: object
	DAMAGE_INDICATOR: object
	DRAGON_BREATH: object
	DRIPPING_LAVA: object
	FALLING_LAVA: object
	LANDING_LAVA: object
	DRIPPING_WATER: object
	FALLING_WATER: object
	EFFECT: object
	ELDER_GUARDIAN: object
	ENCHANTED_HIT: object
	ENCHANT: object
	END_ROD: object
	ENTITY_EFFECT: object
	EXPLOSION_EMITTER: object
	EXPLOSION: object
	SONIC_BOOM: object
	FIREWORK: object
	FISHING: object
	FLAME: object
	CHERRY_LEAVES: object
	SCULK_SOUL: object
	SCULK_CHARGE_POP: object
	SOUL_FIRE_FLAME: object
	SOUL: object
	FLASH: object
	HAPPY_VILLAGER: object
	COMPOSTER: object
	HEART: object
	INSTANT_EFFECT: object
	ITEM_SLIME: object
	ITEM_SNOWBALL: object
	LARGE_SMOKE: object
	LAVA: object
	MYCELIUM: object
	NOTE: object
	POOF: object
	PORTAL: object
	RAIN: object
	SMOKE: object
	SNEEZE: object
	SPIT: object
	SQUID_INK: object
	SWEEP_ATTACK: object
	TOTEM_OF_UNDYING: object
	UNDERWATER: object
	SPLASH: object
	WITCH: object
	BUBBLE_POP: object
	CURRENT_DOWN: object
	BUBBLE_COLUMN_UP: object
	NAUTILUS: object
	DOLPHIN: object
	CAMPFIRE_COSY_SMOKE: object
	CAMPFIRE_SIGNAL_SMOKE: object
	DRIPPING_HONEY: object
	FALLING_HONEY: object
	LANDING_HONEY: object
	FALLING_NECTAR: object
	FALLING_SPORE_BLOSSOM: object
	ASH: object
	CRIMSON_SPORE: object
	WARPED_SPORE: object
	SPORE_BLOSSOM_AIR: object
	DRIPPING_OBSIDIAN_TEAR: object
	FALLING_OBSIDIAN_TEAR: object
	LANDING_OBSIDIAN_TEAR: object
	REVERSE_PORTAL: object
	WHITE_ASH: object
	SMALL_FLAME: object
	SNOWFLAKE: object
	DRIPPING_DRIPSTONE_LAVA: object
	FALLING_DRIPSTONE_LAVA: object
	DRIPPING_DRIPSTONE_WATER: object
	FALLING_DRIPSTONE_WATER: object
	GLOW_SQUID_INK: object
	GLOW: object
	WAX_ON: object
	WAX_OFF: object
	ELECTRIC_SPARK: object
	SCRAPE: object
	EGG_CRACK: object