package com.revolvingmadness.pythonmc.pythonmclibrary.world;

import net.minecraft.particle.ParticleEffect;
import net.minecraft.particle.ParticleTypes;

public enum PyParticles {
    AMBIENT_ENTITY_EFFECT, ANGRY_VILLAGER, BUBBLE, CLOUD, CRIT, DAMAGE_INDICATOR, DRAGON_BREATH, DRIPPING_LAVA, FALLING_LAVA, LANDING_LAVA, DRIPPING_WATER, FALLING_WATER, EFFECT, ELDER_GUARDIAN, ENCHANTED_HIT, ENCHANT, END_ROD, ENTITY_EFFECT, EXPLOSION_EMITTER, EXPLOSION, SONIC_BOOM, FIREWORK, FISHING, FLAME, CHERRY_LEAVES, SCULK_SOUL, SCULK_CHARGE_POP, SOUL_FIRE_FLAME, SOUL, FLASH, HAPPY_VILLAGER, COMPOSTER, HEART, INSTANT_EFFECT, ITEM_SLIME, ITEM_SNOWBALL, LARGE_SMOKE, LAVA, MYCELIUM, NOTE, POOF, PORTAL, RAIN, SMOKE, SNEEZE, SPIT, SQUID_INK, SWEEP_ATTACK, TOTEM_OF_UNDYING, UNDERWATER, SPLASH, WITCH, BUBBLE_POP, CURRENT_DOWN, BUBBLE_COLUMN_UP, NAUTILUS, DOLPHIN, CAMPFIRE_COSY_SMOKE, CAMPFIRE_SIGNAL_SMOKE, DRIPPING_HONEY, FALLING_HONEY, LANDING_HONEY, FALLING_NECTAR, FALLING_SPORE_BLOSSOM, ASH, CRIMSON_SPORE, WARPED_SPORE, SPORE_BLOSSOM_AIR, DRIPPING_OBSIDIAN_TEAR, FALLING_OBSIDIAN_TEAR, LANDING_OBSIDIAN_TEAR, REVERSE_PORTAL, WHITE_ASH, SMALL_FLAME, SNOWFLAKE, DRIPPING_DRIPSTONE_LAVA, FALLING_DRIPSTONE_LAVA, DRIPPING_DRIPSTONE_WATER, FALLING_DRIPSTONE_WATER, GLOW_SQUID_INK, GLOW, WAX_ON, WAX_OFF, ELECTRIC_SPARK, SCRAPE, EGG_CRACK;

    public ParticleEffect toParticle() {
        return switch (this) {
            case AMBIENT_ENTITY_EFFECT -> ParticleTypes.AMBIENT_ENTITY_EFFECT;
            case ANGRY_VILLAGER -> ParticleTypes.ANGRY_VILLAGER;
            case BUBBLE -> ParticleTypes.BUBBLE;
            case CLOUD -> ParticleTypes.CLOUD;
            case CRIT -> ParticleTypes.CRIT;
            case DAMAGE_INDICATOR -> ParticleTypes.DAMAGE_INDICATOR;
            case DRAGON_BREATH -> ParticleTypes.DRAGON_BREATH;
            case DRIPPING_LAVA -> ParticleTypes.DRIPPING_LAVA;
            case FALLING_LAVA -> ParticleTypes.FALLING_LAVA;
            case LANDING_LAVA -> ParticleTypes.LANDING_LAVA;
            case DRIPPING_WATER -> ParticleTypes.DRIPPING_WATER;
            case FALLING_WATER -> ParticleTypes.FALLING_WATER;
            case EFFECT -> ParticleTypes.EFFECT;
            case ELDER_GUARDIAN -> ParticleTypes.ELDER_GUARDIAN;
            case ENCHANTED_HIT -> ParticleTypes.ENCHANTED_HIT;
            case ENCHANT -> ParticleTypes.ENCHANT;
            case END_ROD -> ParticleTypes.END_ROD;
            case ENTITY_EFFECT -> ParticleTypes.ENTITY_EFFECT;
            case EXPLOSION_EMITTER -> ParticleTypes.EXPLOSION_EMITTER;
            case EXPLOSION -> ParticleTypes.EXPLOSION;
            case SONIC_BOOM -> ParticleTypes.SONIC_BOOM;
            case FIREWORK -> ParticleTypes.FIREWORK;
            case FISHING -> ParticleTypes.FISHING;
            case FLAME -> ParticleTypes.FLAME;
            case CHERRY_LEAVES -> ParticleTypes.CHERRY_LEAVES;
            case SCULK_SOUL -> ParticleTypes.SCULK_SOUL;
            case SCULK_CHARGE_POP -> ParticleTypes.SCULK_CHARGE_POP;
            case SOUL_FIRE_FLAME -> ParticleTypes.SOUL_FIRE_FLAME;
            case SOUL -> ParticleTypes.SOUL;
            case FLASH -> ParticleTypes.FLASH;
            case HAPPY_VILLAGER -> ParticleTypes.HAPPY_VILLAGER;
            case COMPOSTER -> ParticleTypes.COMPOSTER;
            case HEART -> ParticleTypes.HEART;
            case INSTANT_EFFECT -> ParticleTypes.INSTANT_EFFECT;
            case ITEM_SLIME -> ParticleTypes.ITEM_SLIME;
            case ITEM_SNOWBALL -> ParticleTypes.ITEM_SNOWBALL;
            case LARGE_SMOKE -> ParticleTypes.LARGE_SMOKE;
            case LAVA -> ParticleTypes.LAVA;
            case MYCELIUM -> ParticleTypes.MYCELIUM;
            case NOTE -> ParticleTypes.NOTE;
            case POOF -> ParticleTypes.POOF;
            case PORTAL -> ParticleTypes.PORTAL;
            case RAIN -> ParticleTypes.RAIN;
            case SMOKE -> ParticleTypes.SMOKE;
            case SNEEZE -> ParticleTypes.SNEEZE;
            case SPIT -> ParticleTypes.SPIT;
            case SQUID_INK -> ParticleTypes.SQUID_INK;
            case SWEEP_ATTACK -> ParticleTypes.SWEEP_ATTACK;
            case TOTEM_OF_UNDYING -> ParticleTypes.TOTEM_OF_UNDYING;
            case UNDERWATER -> ParticleTypes.UNDERWATER;
            case SPLASH -> ParticleTypes.SPLASH;
            case WITCH -> ParticleTypes.WITCH;
            case BUBBLE_POP -> ParticleTypes.BUBBLE_POP;
            case CURRENT_DOWN -> ParticleTypes.CURRENT_DOWN;
            case BUBBLE_COLUMN_UP -> ParticleTypes.BUBBLE_COLUMN_UP;
            case NAUTILUS -> ParticleTypes.NAUTILUS;
            case DOLPHIN -> ParticleTypes.DOLPHIN;
            case CAMPFIRE_COSY_SMOKE -> ParticleTypes.CAMPFIRE_COSY_SMOKE;
            case CAMPFIRE_SIGNAL_SMOKE -> ParticleTypes.CAMPFIRE_SIGNAL_SMOKE;
            case DRIPPING_HONEY -> ParticleTypes.DRIPPING_HONEY;
            case FALLING_HONEY -> ParticleTypes.FALLING_HONEY;
            case LANDING_HONEY -> ParticleTypes.LANDING_HONEY;
            case FALLING_NECTAR -> ParticleTypes.FALLING_NECTAR;
            case FALLING_SPORE_BLOSSOM -> ParticleTypes.FALLING_SPORE_BLOSSOM;
            case ASH -> ParticleTypes.ASH;
            case CRIMSON_SPORE -> ParticleTypes.CRIMSON_SPORE;
            case WARPED_SPORE -> ParticleTypes.WARPED_SPORE;
            case SPORE_BLOSSOM_AIR -> ParticleTypes.SPORE_BLOSSOM_AIR;
            case DRIPPING_OBSIDIAN_TEAR -> ParticleTypes.DRIPPING_OBSIDIAN_TEAR;
            case FALLING_OBSIDIAN_TEAR -> ParticleTypes.FALLING_OBSIDIAN_TEAR;
            case LANDING_OBSIDIAN_TEAR -> ParticleTypes.LANDING_OBSIDIAN_TEAR;
            case REVERSE_PORTAL -> ParticleTypes.REVERSE_PORTAL;
            case WHITE_ASH -> ParticleTypes.WHITE_ASH;
            case SMALL_FLAME -> ParticleTypes.SMALL_FLAME;
            case SNOWFLAKE -> ParticleTypes.SNOWFLAKE;
            case DRIPPING_DRIPSTONE_LAVA -> ParticleTypes.DRIPPING_DRIPSTONE_LAVA;
            case FALLING_DRIPSTONE_LAVA -> ParticleTypes.FALLING_DRIPSTONE_LAVA;
            case DRIPPING_DRIPSTONE_WATER -> ParticleTypes.DRIPPING_DRIPSTONE_WATER;
            case FALLING_DRIPSTONE_WATER -> ParticleTypes.FALLING_DRIPSTONE_WATER;
            case GLOW_SQUID_INK -> ParticleTypes.GLOW_SQUID_INK;
            case GLOW -> ParticleTypes.GLOW;
            case WAX_ON -> ParticleTypes.WAX_ON;
            case WAX_OFF -> ParticleTypes.WAX_OFF;
            case ELECTRIC_SPARK -> ParticleTypes.ELECTRIC_SPARK;
            case SCRAPE -> ParticleTypes.SCRAPE;
            case EGG_CRACK -> ParticleTypes.EGG_CRACK;
        };
    }
}
